block-beta
columns 3
  playground["playground"]
  space
  space
  ginga_node["ginga-node"]
  ginga_code["ginga-code"]
  space
  web["gingaf (web)"]
  desktop["gingaf (desktop)"]
  mobile["gingaf (mobile)"]
  gingaf["gingaf"]:3
  nclui["nclui"]:3
  ncldoc["ncldoc"]:2
  gingacc["gingacc"]:1
