name: Publish VS Code Extension

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./ginga-vscode
        run: npm install --no-audit --no-fund

      - name: Publish VS Code Extension
        working-directory: ./ginga-vscode
        run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }}
